name: 'pnpm Install'
description: 'Install pnpm for a particular folder in a workspace and use a cache. Intended to be run in a Node Docker container.'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.2
      name: Install pnpm
      with:
        version: 7
        run_install: false

    - name: Install dependencies
      shell: sh
      run: |
        pnpm install --frozen-lockfile
