name: Build Lint and Test Beet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-lint-and-test-beet:
    runs-on: ubuntu-20.04
    container: node:18.3.0-alpine3.14
    env:
      CI: true

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install PNPM and dependencies
      uses: ./.github/actions/pnpm-install
    - name: Install PNPM and dependencies
      run: apk update && apk add python3 g++ make && rm -rf /var/cache/apk/* && npm i pnpm@7.4.0 -g && pnpm install
    - name: TSC
      run: pnpm run tsc
    - name: Test
      run: pnpm run tsc -p tsconfig.test.json && pnpm run test
